### PR TITLE
GenerateVCFirstAttempt

### PR DESCRIPTION
**Pull request by MathumithaVe**
DVLA Driving Licence Generate VC with valid DL number and save  save check the document number is same as given Driving Licence in attempt 1 happy path
DVLA Driving Licence Generate VC with invalid DL number and save check the document number is same as given Driving Licence in attempt 2 unhappy path
DVLA Driving Licence Generate VC with invalid DL number and save check the document number is same as given Driving Licence prove in another way unhappy path
DVA Driving Licence Generate VC with valid DL number and save  save check the document number is same as given Driving Licence in attempt 1 happy path
DVA Driving Licence Generate VC with invalid DL number and save check the document number is same as given Driving Licence in attempt 2 unhappy path
DVA Driving Licence Generate VC with invalid DL number and save check the document number is same as given Driving Licence prove in another way unhappy path

### CODE REVIEW

**Comment by chinmayi-gds** [comment]
@MathumithaVe Just had another at this pull request. I think we don't need separate tests for this. Just an additional test step to the existing tests makes more sense to me. 
We can either make a change to the existing test method to check for the Json response or add an additional test step to the existing tests?

**Comment by chinmayi-gds** [comment]
public void scoreIs(String validityScore, String strengthScore) throws IOException {
    String result = JSONPayload.getText();
    LOGGER.info("result = " + result);
    ObjectMapper objectMapper = new ObjectMapper();
    JsonNode jsonNode = objectMapper.readTree(result);
    JsonNode vcNode = jsonNode.get("vc");
    JsonNode evidenceNode = vcNode.get("evidence");

    ObjectReader objectReader =
            new ObjectMapper().readerFor(new TypeReference<List<JsonNode>>() {});
    List<JsonNode> evidence = objectReader.readValue(evidenceNode);

    String ValidityScore = evidence.get(0).get("validityScore").asText();
    assertEquals(ValidityScore, validityScore);

    String StrengthScore = evidence.get(0).get("strengthScore").asText();
    assertEquals(StrengthScore, strengthScore);

    String licenceNumber = evidence.get(0).get("documentNumber").asText();
    assertEquals(licenceNumber, documentNumber);

}

**Comment by MathumithaVe** [comment]
@chinmayi-gds The reason for creating a separate feature. I don’t want to disturb the already existing test which I confirmed with you already. If that’s the best practice I will go with that and add to the existing test.

**Comment by gds-jbentham** [comment]
> @MathumithaVe Just had another look at this pull request. I think we don't need separate tests for this. Just an additional test step to the existing tests makes more sense to me. We can either make a change to the existing test method to check for the Json response or add an additional test step to the existing tests to check for that additional field on the VC?
> 
> @gds-jbentham What are your thoughts?

Im happy for this to be another test as we want to check the VC is present when the user selects prove identity another way

**Review by gds-jbentham — APPROVED** [review]

**Pull request merged**
